# Generated by Django 2.2.6 on 2019-11-23 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0002_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='aaaaaaaaaaaaaaaa', to='datamodel.Game'),
        ),
    ]
