# Generated by Django 2.2.6 on 2019-11-24 17:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0006_auto_20191123_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='game',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='datamodel.Game'),
        ),
        migrations.AlterField(
            model_name='move',
            name='origin',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(
                0), django.core.validators.MaxValueValidator(63)]),
        ),
        migrations.AlterField(
            model_name='move',
            name='target',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(
                0), django.core.validators.MaxValueValidator(63)]),
        ),
    ]
