# Generated by Django 2.2.6 on 2019-11-25 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0007_auto_20191124_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cat_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='games_as_cat', to=settings.AUTH_USER_MODEL),
        ),
    ]
