# Generated by Django 2.2.6 on 2019-11-26 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0008_auto_20191125_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='game',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='datamodel.Game'),
        ),
        migrations.AlterField(
            model_name='move',
            name='origin',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='move',
            name='target',
            field=models.IntegerField(),
        ),
    ]
